### ISSUE TITLE
Enhancements for scanner plugin tutorial

### ISSUE THREAD

**Issue by DirkMahler** [buschmais/jqassistant-101#11]
- Rules for exception handling
- Starting a Neo4j Browser for manually inspecting generated graphs
- Guidelines 
  - graph modelling (e.g. multiple labels, naming of labels and relationships)
  - for tests (e.g. unit vs. IT)
- Link to XO documentation instead of project homepage
- Plugin configuration
- Finding existing nodes/relations using indexed properties or queries
- Caching of nodes vs. database lookups
- Work with scopes

**Comment by StephanPirnbaum** [comment]
We're currently rebuilding the 101s, so closing this for now.
